-- @author mdpinar

-- healthy implementations
insert into platform (name, domain, country, class_name, currency_code, currency_format) values
  ('Test-1 TR', 'sanal.com', 'Turkey', 'zz.Sanal', 'TRY', '#,##0.00 TL'),
  ('Amazon US', 'amazon.com', 'United States', 'xx.Amazon', 'USD', '$#,##0.00'),
  ('Amazon UK', 'amazon.co.uk', 'United Kingdom', 'xx.Amazon', 'GBP', '£#,##0.00'),
  ('Amazon CA', 'amazon.ca', 'Canada', 'xx.Amazon', 'CAD', '$#,##0.00'),
  ('Amazon AU', 'amazon.com.au', 'Australia', 'xx.Amazon', 'AUD', '$#,##0.00'),
  ('Amazon DE', 'amazon.de', 'Germany', 'xx.Amazon', 'EUR', '#,##0.00 €'),
  ('Amazon NL', 'amazon.nl', 'Netherlands', 'xx.Amazon', 'EUR', '€ #,##0.00'),
  ('Amazon FR', 'amazon.fr', 'France', 'xx.Amazon', 'EUR', '#,##0.00 €'),
  ('Amazon IT', 'amazon.it', 'Italy', 'xx.Amazon', 'EUR', '€ #,##0.00'),
  ('Amazon ES', 'amazon.es', 'Spain', 'xx.Amazon', 'EUR', '€ #,##0.00'),
  ('Amazon TR', 'amazon.com.tr', 'Turkey', 'xx.Amazon', 'TRY', '#,##0.00 TL'),
  ('Ebay US', 'ebay.com', 'United States', 'xx.Ebay', 'USD', '$#,##0.00'),
  ('Ebay UK', 'ebay.co.uk', 'United Kingdom', 'xx.Ebay', 'GBP', '£#,##0.00'),
  ('Ebay CA', 'ebay.ca', 'Canada', 'xx.Ebay', 'CAD', '$#,##0.00'),
  ('Ebay AU', 'ebay.com.au', 'Australia', 'xx.Ebay', 'AUD', '$#,##0.00'),
  ('Ebay DE', 'ebay.de', 'Germany', 'xx.Ebay', 'EUR', '#,##0.00 €'),
  ('Ebay NL', 'ebay.nl', 'Netherlands', 'xx.Ebay', 'EUR', '€ #,##0.00'),
  ('Ebay FR', 'ebay.fr', 'France', 'xx.Ebay', 'EUR', '#,##0.00 €'),
  ('Ebay IT', 'ebay.it', 'Italy', 'xx.Ebay', 'EUR', '€ #,##0.00'),
  ('Ebay ES', 'ebay.es', 'Spain', 'xx.Ebay', 'EUR', '€ #,##0.00'),
  ('Apple US', 'apple.com/us-hed', 'United States', 'xx.Apple', 'USD', '$#,##0.00'),
  ('Apple UK', 'apple.com/uk', 'United Kingdom', 'xx.Apple', 'GBP', '£#,##0.00'),
  ('Apple CA', 'apple.com/ca', 'Canada', 'xx.Apple', 'CAD', '$#,##0.00'),
  ('Apple AU', 'apple.com/au', 'Australia', 'xx.Apple', 'AUD', '$#,##0.00'),
  ('Apple DE', 'apple.com/de', 'Germany', 'xx.Apple', 'EUR', '#,##0.00 €'),
  ('Apple NL', 'apple.com/nl', 'Netherlands', 'xx.Apple', 'EUR', '€ #,##0.00'),
  ('Apple FR', 'apple.com/fr', 'France', 'xx.Apple', 'EUR', '#,##0.00 €'),
  ('Apple IT', 'apple.com/it', 'Italy', 'xx.Apple', 'EUR', '€ #,##0.00'),
  ('Apple ES', 'apple.com/es', 'Spain', 'xx.Apple', 'EUR', '€ #,##0.00'),
  ('Apple TR', 'apple.com/tr', 'Turkey', 'xx.Apple', 'TRY', '#,##0.00 TL'),
  ('Lidl US', 'lidl.com', 'United States', 'us.Lidl', 'USD', '$#,##0.00'),
  ('Lidl UK', 'lidl.co.uk', 'United Kingdom', 'xx.Lidl', 'GBP', '£#,##0.00'),
  ('Lidl DE', 'lidl.de', 'Germany', 'xx.Lidl', 'EUR', '#,##0.00 €'),
  ('Lidl NL', 'lidl.nl', 'Netherlands', 'xx.Lidl', 'EUR', '€ #,##0.00'),
  ('Lidl FR', 'lidl.fr', 'France', 'xx.Lidl', 'EUR', '#,##0.00 €'),
  ('Lidl IT', 'lidl.it', 'Italy', 'xx.Lidl', 'EUR', '€ #,##0.00'),
  ('Lidl ES', 'lidl.es', 'Spain', 'xx.Lidl', 'EUR', '€ #,##0.00'),
  ('MediaMarkt DE', 'mediamarkt.de', 'Germany', 'de.MediaMarkt', 'EUR', '#,##0.00 €'),
  ('MediaMarkt NL', 'mediamarkt.nl', 'Netherlands', 'xx.MediaMarkt', 'EUR', '€ #,##0.00'),
  ('MediaMarkt ES', 'mediamarkt.es', 'Spain', 'xx.MediaMarkt', 'EUR', '€ #,##0.00'),
  ('MediaMarkt TR', 'mediamarkt.com.tr', 'Turkey', 'xx.MediaMarkt', 'TRY', '#,##0.00 TL'),
  ('Saturn DE', 'saturn.de', 'Germany', 'de.MediaMarkt', 'EUR', '#,##0.00 €'),
  ('Zalando UK', 'zalando.co.uk', 'United Kingdom', 'xx.Zalando', 'GBP', '£#,##0.00'),
  ('Zalando DE', 'zalando.de', 'Germany', 'xx.Zalando', 'EUR', '#,##0.00 €'),
  ('Zalando NL', 'zalando.nl', 'Netherlands', 'xx.Zalando', 'EUR', '€ #,##0.00'),
  ('Zalando FR', 'zalando.fr', 'France', 'xx.Zalando', 'EUR', '#,##0.00 €'),
  ('Zalando IT', 'zalando.it', 'Italy', 'xx.Zalando', 'EUR', '€ #,##0.00'),
  ('Zalando ES', 'zalando.es', 'Spain', 'xx.Zalando', 'EUR', '€ #,##0.00'),
  ('Bonprix UK', 'bonprix.co.uk', 'United Kingdom', 'xx.Bonprix', 'GBP', '£#,##0.00'),
  ('Bonprix DE', 'bonprix.de', 'Germany', 'xx.Bonprix', 'EUR', '#,##0.00 €'),
  ('Bonprix NL', 'bonprix.nl', 'Netherlands', 'xx.Bonprix', 'EUR', '€ #,##0.00'),
  ('Bonprix FR', 'bonprix.fr', 'France', 'xx.Bonprix', 'EUR', '#,##0.00 €'),
  ('Bonprix IT', 'bonprix.it', 'Italy', 'xx.Bonprix', 'EUR', '€ #,##0.00'),
  ('BigW AU', 'bigw.com.au', 'Australia', 'au.BigW', 'AUD', '$#,##0.00'),
  ('Kogan AU', 'kogan.com', 'Australia', 'au.Kogan', 'AUD', '$#,##0.00'),
  ('The Good Guys AU', 'thegoodguys.com.au', 'Australia', 'au.TheGoodGuys', 'AUD', '$#,##0.00'),
  ('Appliances Online AU', 'appliancesonline.com.au', 'Australia', 'au.AppliancesOnline', 'AUD', '$#,##0.00'),
  ('BestBuy CA', 'bestbuy.ca', 'Canada', 'ca.BestBuy', 'CAD', '$#,##0.00'),
  ('BestBuy US', 'bestbuy.com', 'United States', 'us.BestBuy', 'USD', '$#,##0.00'),
  ('Canadian Tire CA', 'canadiantire.ca', 'Canada', 'ca.CanadianTire', 'CAD', '$#,##0.00'),
  ('Walmart CA', 'walmart.ca', 'Canada', 'ca.Walmart', 'CAD', '$#,##0.00'),
  ('Notebooks Billiger DE', 'notebooksbilliger.de', 'Germany', 'de.NotebooksBilliger', 'EUR', '#,##0.00 €'),
  ('Otto DE', 'otto.de', 'Germany', 'de.Otto', 'EUR', '#,##0.00 €'),
  ('Electro King ES', 'electroking.es', 'Spain', 'es.ElectroKing', 'EUR', '€ #,##0.00'),
  ('101 Gigas ES', '101gigas.com', 'Spain', 'es.Gigas101', 'EUR', '€ #,##0.00'),
  ('UlaBox ES', 'ulabox.com', 'Spain', 'es.UlaBox', 'EUR', '€ #,##0.00'),
  ('Auchan FR', 'auchan.fr', 'France', 'fr.Auchan', 'EUR', '#,##0.00 €'),
  ('CDiscount FR', 'cdiscount.com', 'France', 'fr.CDiscount', 'EUR', '#,##0.00 €'),
  ('Fnac FR', 'fnac.com', 'France', 'fr.Fnac', 'EUR', '#,##0.00 €'),
  ('Laredoute FR', 'laredoute.fr', 'France', 'fr.Laredoute', 'EUR', '#,##0.00 €'),
  ('EPrice IT', 'eprice.it', 'Italy', 'it.EPrice', 'EUR', '€ #,##0.00'),
  ('Euronics IT', 'euronics.it', 'Italy', 'it.Euronics', 'EUR', '€ #,##0.00'),
  ('Euronics DE', 'euronics.de', 'Germany', 'de.Euronics', 'EUR', '#,##0.00 €'),
  ('Euronics UK', 'euronics.co.uk', 'United Kingdom', 'uk.Euronics', 'GBP', '£#,##0.00'),
  ('Euronics ES', 'euronics.es', 'Spain', 'es.Euronics', 'EUR', '€ #,##0.00'),
  ('MediaWorld IT', 'mediaworld.it', 'Italy', 'it.MediaWorld', 'EUR', '€ #,##0.00'),
  ('VidaXL IT', 'vidaxl.it', 'Italy', 'xx.VidaXL', 'EUR', '€ #,##0.00'),
  ('VidaXL US', 'vidaxl.us', 'United States', 'xx.VidaXL', 'USD', '$#,##0.00'),
  ('Bol NL', 'bol.com', 'Netherlands', 'nl.Bol', 'EUR', '€ #,##0.00'),
  ('CoolBlue NL', 'coolblue.nl', 'Netherlands', 'nl.CoolBlue', 'EUR', '€ #,##0.00'),
  ('De Bijenkorf NL', 'debijenkorf.nl', 'Netherlands', 'nl.DeBijenkorf', 'EUR', '€ #,##0.00'),
  ('Wehkamp NL', 'wehkamp.nl', 'Netherlands', 'nl.Wehkamp', 'EUR', '€ #,##0.00'),
  ('Gittigidiyor TR', 'gittigidiyor.com', 'Turkey', 'tr.GittiGidiyor', 'TRY', '#,##0.00 TL'),
  ('Hepsiburada TR', 'hepsiburada.com', 'Turkey', 'tr.HepsiBurada', 'TRY', '#,##0.00 TL'),
  ('n11 TR', 'n11.com', 'Turkey', 'tr.N11', 'TRY', '#,##0.00 TL'),
  ('Teknosa TR', 'teknosa.com', 'Turkey', 'tr.Teknosa', 'TRY', '#,##0.00 TL'),
  ('Trendyol TR', 'trendyol.com', 'Turkey', 'tr.Trendyol', 'TRY', '#,##0.00 TL'),
  ('Argos UK', 'argos.co.uk', 'United Kingdom', 'uk.Argos', 'GBP', '£#,##0.00'),
  ('Asda UK', 'groceries.argos.com', 'United Kingdom', 'uk.Asda', 'GBP', '£#,##0.00'),
  ('Asos UK', 'asos.com', 'United Kingdom', 'uk.Asos', 'GBP', '£#,##0.00'),
  ('Currys UK', 'currys.co.uk', 'United Kingdom', 'uk.Currys', 'GBP', '£#,##0.00'),
  ('Debenhams UK', 'debenhams.com', 'United Kingdom', 'uk.Debenhams', 'GBP', '£#,##0.00'),
  ('NewLook UK', 'newlook.com', 'United Kingdom', 'uk.NewLook', 'GBP', '£#,##0.00'),
  ('Zavvi UK', 'zavvi.com', 'United Kingdom', 'uk.Zavvi', 'GBP', '£#,##0.00'),
  ('Harvey Norman AU', 'harveynorman.com.au', 'Australia', 'au.HarveyNorman', 'AUD', '$#,##0.00')
  ;
