-- @author mdpinar

-- healthy implementations
insert into platform (name, domain, country, class_name) values
  ('Test 01', 'sanal.com', 'Turkey', 'zz.Sanal'),
  ('Amazon US', 'amazon.com', 'United States', 'xx.Amazon'),
  ('Amazon UK', 'amazon.co.uk', 'United Kingdom', 'xx.Amazon'),
  ('Amazon CA', 'amazon.ca', 'Canada', 'xx.Amazon'),
  ('Amazon AU', 'amazon.com.au', 'Australia', 'xx.Amazon'),
  ('Amazon DE', 'amazon.de', 'Germany', 'xx.Amazon'),
  ('Amazon NL', 'amazon.nl', 'Netherlands', 'xx.Amazon'),
  ('Amazon FR', 'amazon.fr', 'France', 'xx.Amazon'),
  ('Amazon IT', 'amazon.it', 'Italy', 'xx.Amazon'),
  ('Amazon ES', 'amazon.es', 'Spain', 'xx.Amazon'),
  ('Amazon TR', 'amazon.com.tr', 'Turkey', 'xx.Amazon'),
  ('Ebay US', 'ebay.com', 'United States', 'xx.Ebay'),
  ('Ebay UK', 'ebay.co.uk', 'United Kingdom', 'xx.Ebay'),
  ('Ebay CA', 'ebay.ca', 'Canada', 'xx.Ebay'),
  ('Ebay AU', 'ebay.com.au', 'Australia', 'xx.Ebay'),
  ('Ebay DE', 'ebay.de', 'Germany', 'xx.Ebay'),
  ('Ebay NL', 'ebay.nl', 'Netherlands', 'xx.Ebay'),
  ('Ebay FR', 'ebay.fr', 'France', 'xx.Ebay'),
  ('Ebay IT', 'ebay.it', 'Italy', 'xx.Ebay'),
  ('Ebay ES', 'ebay.es', 'Spain', 'xx.Ebay'),
  ('Apple US', 'apple.com/us-hed', 'United States', 'xx.Apple'),
  ('Apple UK', 'apple.com/uk', 'United Kingdom', 'xx.Apple'),
  ('Apple CA', 'apple.com/ca', 'Canada', 'xx.Apple'),
  ('Apple AU', 'apple.com/au', 'Australia', 'xx.Apple'),
  ('Apple DE', 'apple.com/de', 'Germany', 'xx.Apple'),
  ('Apple NL', 'apple.com/nl', 'Netherlands', 'xx.Apple'),
  ('Apple FR', 'apple.com/fr', 'France', 'xx.Apple'),
  ('Apple IT', 'apple.com/it', 'Italy', 'xx.Apple'),
  ('Apple ES', 'apple.com/es', 'Spain', 'xx.Apple'),
  ('Apple TR', 'apple.com/tr', 'Turkey', 'xx.Apple'),
  ('Lidl US', 'lidl.com', 'United States', 'us.Lidl'),
  ('Lidl UK', 'lidl.co.uk', 'United Kingdom', 'xx.Lidl'),
  ('Lidl DE', 'lidl.de', 'Germany', 'xx.Lidl'),
  ('Lidl NL', 'lidl.nl', 'Netherlands', 'xx.Lidl'),
  ('Lidl FR', 'lidl.fr', 'France', 'xx.Lidl'),
  ('Lidl IT', 'lidl.it', 'Italy', 'xx.Lidl'),
  ('Lidl ES', 'lidl.es', 'Spain', 'xx.Lidl'),
  ('MediaMarkt DE', 'mediamarkt.de', 'Germany', 'de.MediaMarkt'),
  ('MediaMarkt NL', 'mediamarkt.nl', 'Netherlands', 'xx.MediaMarkt'),
  ('MediaMarkt ES', 'mediamarkt.es', 'Spain', 'xx.MediaMarkt'),
  ('MediaMarkt TR', 'mediamarkt.com.tr', 'Turkey', 'xx.MediaMarkt'),
  ('Saturn DE', 'saturn.de', 'Germany', 'de.MediaMarkt'),
  ('Zalando UK', 'zalando.co.uk', 'United Kingdom', 'xx.Zalando'),
  ('Zalando DE', 'zalando.de', 'Germany', 'xx.Zalando'),
  ('Zalando NL', 'zalando.nl', 'Netherlands', 'xx.Zalando'),
  ('Zalando FR', 'zalando.fr', 'France', 'xx.Zalando'),
  ('Zalando IT', 'zalando.it', 'Italy', 'xx.Zalando'),
  ('Zalando ES', 'zalando.es', 'Spain', 'xx.Zalando'),
  ('Bonprix UK', 'bonprix.co.uk', 'United Kingdom', 'xx.Bonprix'),
  ('Bonprix DE', 'bonprix.de', 'Germany', 'xx.Bonprix'),
  ('Bonprix NL', 'bonprix.nl', 'Netherlands', 'xx.Bonprix'),
  ('Bonprix FR', 'bonprix.fr', 'France', 'xx.Bonprix'),
  ('Bonprix IT', 'bonprix.it', 'Italy', 'xx.Bonprix'),
  ('BigW AU', 'bigw.com.au', 'Australia', 'au.BigW'),
  ('Kogan AU', 'kogan.com', 'Australia', 'au.Kogan'),
  ('The Good Guys AU', 'thegoodguys.com.au', 'Australia', 'au.TheGoodGuys'),
  ('Appliances Online AU', 'appliancesonline.com.au', 'Australia', 'au.AppliancesOnline'),
  ('BestBuy CA', 'bestbuy.ca', 'Canada', 'ca.BestBuy'),
  ('BestBuy US', 'bestbuy.com', 'United States', 'us.BestBuy'),
  ('Canadian Tire CA', 'canadiantire.ca', 'Canada', 'ca.CanadianTire'),
  ('Walmart CA', 'walmart.ca', 'Canada', 'ca.Walmart'),
  ('Notebooks Billiger DE', 'notebooksbilliger.de', 'Germany', 'de.NotebooksBilliger'),
  ('Otto DE', 'otto.de', 'Germany', 'de.Otto'),
  ('Electro King ES', 'electroking.es', 'Spain', 'es.ElectroKing'),
  ('101 Gigas ES', '101gigas.com', 'Spain', 'es.Gigas101'),
  ('UlaBox ES', 'ulabox.com', 'Spain', 'es.UlaBox'),
  ('Auchan FR', 'auchan.fr', 'France', 'fr.Auchan'),
  ('CDiscount FR', 'cdiscount.com', 'France', 'fr.CDiscount'),
  ('Fnac FR', 'fnac.com', 'France', 'fr.Fnac'),
  ('Laredoute FR', 'laredoute.fr', 'France', 'fr.Laredoute'),
  ('EPrice IT', 'eprice.it', 'Italy', 'it.EPrice'),
  ('Euronics IT', 'euronics.it', 'Italy', 'it.Euronics'),
  ('Euronics DE', 'euronics.de', 'Germany', 'de.Euronics'),
  ('Euronics UK', 'euronics.co.uk', 'United Kingdom', 'uk.Euronics'),
  ('Euronics ES', 'euronics.es', 'Spain', 'es.Euronics'),
  ('MediaWorld IT', 'mediaworld.it', 'Italy', 'it.MediaWorld'),
  ('VidaXL IT', 'vidaxl.it', 'Italy', 'xx.VidaXL'),
  ('VidaXL US', 'vidaxl.us', 'United States', 'xx.VidaXL'),
  ('Bol NL', 'bol.com', 'Netherlands', 'nl.Bol'),
  ('CoolBlue NL', 'coolblue.nl', 'Netherlands', 'nl.CoolBlue'),
  ('De Bijenkorf NL', 'debijenkorf.nl', 'Netherlands', 'nl.DeBijenkorf'),
  ('Wehkamp NL', 'wehkamp.nl', 'Netherlands', 'nl.Wehkamp'),
  ('Gittigidiyor TR', 'gittigidiyor.com', 'Turkey', 'tr.GittiGidiyor'),
  ('Hepsiburada TR', 'hepsiburada.com', 'Turkey', 'tr.HepsiBurada'),
  ('n11 TR', 'n11.com', 'Turkey', 'tr.N11'),
  ('Teknosa TR', 'teknosa.com', 'Turkey', 'tr.Teknosa'),
  ('Trendyol TR', 'trendyol.com', 'Turkey', 'tr.Trendyol'),
  ('Argos UK', 'argos.co.uk', 'United Kingdom', 'uk.Argos'),
  ('Asda UK', 'groceries.argos.com', 'United Kingdom', 'uk.Asda'),
  ('Asos UK', 'asos.com', 'United Kingdom', 'uk.Asos'),
  ('Currys UK', 'currys.co.uk', 'United Kingdom', 'uk.Currys'),
  ('Debenhams UK', 'debenhams.com', 'United Kingdom', 'uk.Debenhams'),
  ('NewLook UK', 'newlook.com', 'United Kingdom', 'uk.NewLook'),
  ('Zavvi UK', 'zavvi.com', 'United Kingdom', 'uk.Zavvi'),
  ('Harvey Norman AU', 'harveynorman.com.au', 'Australia', 'au.HarveyNorman')
  ;
