-- @author mdpinar

-- healthy implementations
insert into platform (name, domain, country, class_name) values
  ('Test 01', 'sanal.com', 'Turkey', 'zz.Sanal'),
  ('Amazon US', 'amazon.com', 'United States', 'us.AmazonUS'),
  ('Amazon UK', 'amazon.co.uk', 'United Kingdom', 'uk.AmazonUK'),
  ('Amazon CA', 'amazon.ca', 'Canada', 'ca.AmazonCA'),
  ('Amazon AU', 'amazon.com.au', 'Australia', 'au.AmazonAU'),
  ('Amazon DE', 'amazon.de', 'Germany', 'de.AmazonDE'),
  ('Amazon NL', 'amazon.nl', 'Netherlands', 'nl.AmazonNL'),
  ('Amazon FR', 'amazon.fr', 'France', 'fr.AmazonFR'),
  ('Amazon IT', 'amazon.it', 'Italy', 'it.AmazonIT'),
  ('Amazon ES', 'amazon.es', 'Spain', 'es.AmazonES'),
  ('Amazon TR', 'amazon.com.tr', 'Turkey', 'tr.AmazonTR'),
  ('Ebay US', 'ebay.com', 'United States', 'us.EbayUS'),
  ('Ebay UK', 'ebay.co.uk', 'United Kingdom', 'uk.EbayUK'),
  ('Ebay CA', 'ebay.ca', 'Canada', 'ca.EbayCA'),
  ('Ebay AU', 'ebay.com.au', 'Australia', 'au.EbayAU'),
  ('Ebay DE', 'ebay.de', 'Germany', 'de.EbayDE'),
  ('Ebay NL', 'ebay.nl', 'Netherlands', 'nl.EbayNL'),
  ('Ebay FR', 'ebay.fr', 'France', 'fr.EbayFR'),
  ('Ebay IT', 'ebay.it', 'Italy', 'it.EbayIT'),
  ('Ebay ES', 'ebay.es', 'Spain', 'es.EbayES'),
  ('Apple US', 'apple.com', 'United States', 'us.AppleUS'),
  ('Apple UK', 'apple.com/uk', 'United Kingdom', 'uk.AmazonUK'),
  ('Apple CA', 'apple.com/ca', 'Canada', 'ca.AmazonCA'),
  ('Apple AU', 'apple.com/au', 'Australia', 'au.AmazonAU'),
  ('Apple DE', 'apple.com/de', 'Germany', 'de.AmazonDE'),
  ('Apple NL', 'apple.com/nl', 'Netherlands', 'nl.AmazonNL'),
  ('Apple FR', 'apple.com/fr', 'France', 'fr.AmazonFR'),
  ('Apple IT', 'apple.com/it', 'Italy', 'it.AmazonIT'),
  ('Apple ES', 'apple.com/es', 'Spain', 'es.AmazonES'),
  ('Apple TR', 'apple.com/tr', 'Turkey', 'tr.AmazonTR'),
  ('Lidl US', 'lidl.com', 'United States', 'us.Lidl'),
  ('Lidl UK', 'lidl.co.uk', 'United Kingdom', 'uk.LidlUK'),
  ('Lidl DE', 'lidl.de', 'Germany', 'de.LidlDE'),
  ('Lidl NL', 'lidl.nl', 'Netherlands', 'nl.LidlNL'),
  ('Lidl FR', 'lidl.fr', 'France', 'fr.LidlFR'),
  ('Lidl IT', 'lidl.it', 'Italy', 'it.LidlIT'),
  ('Lidl ES', 'lidl.es', 'Spain', 'es.LidlES'),
  ('MediaMarkt DE', 'mediamarkt.de', 'Germany', 'de.MediaMarkt'),
  ('MediaMarkt NL', 'mediamarkt.nl', 'Netherlands', 'nl.MediaMarktNL'),
  ('MediaMarkt ES', 'mediamarkt.es', 'Spain', 'es.MediaMarktES'),
  ('MediaMarkt TR', 'mediamarkt.com.tr', 'Turkey', 'tr.MediaMarktTR'),
  ('Zalando UK', 'zalando.co.uk', 'United Kingdom', 'uk.ZalandoUK'),
  ('Zalando DE', 'zalando.de', 'Germany', 'de.ZalandoDE'),
  ('Zalando NL', 'zalando.nl', 'Netherlands', 'nl.ZalandoNL'),
  ('Zalando FR', 'zalando.fr', 'France', 'fr.ZalandoFR'),
  ('Zalando IT', 'zalando.it', 'Italy', 'it.ZalandoIT'),
  ('Zalando ES', 'zalando.es', 'Spain', 'es.ZalandoES'),
  ('Bonprix UK', 'bonprix.co.uk', 'United Kingdom', 'uk.BonprixUK'),
  ('Bonprix DE', 'bonprix.de', 'Germany', 'de.BonprixDE'),
  ('Bonprix NL', 'bonprix.nl', 'Netherlands', 'nl.BonprixNL'),
  ('Bonprix FR', 'bonprix.fr', 'France', 'fr.BonprixFR'),
  ('Bonprix IT', 'bonprix.it', 'Italy', 'it.BonprixIT'),
  ('Rakuten DE', 'rakuten.de', 'Germany', 'de.RakutenDE'),
  ('Rakuten FR', 'fr.shopping.rakuten.com', 'France', 'fr.RakutenFR'),
  ('BigW AU', 'bigw.com.au', 'Australia', 'au.BigW'),
  ('Kogan AU', 'kogan.com', 'Australia', 'au.Kogan'),
  ('The Good Guys AU', 'thegoodguys.com.au', 'Australia', 'au.TheGoodGuys'),
  ('Appliances Online AU', 'appliancesonline.com.au', 'Australia', 'au.AppliancesOnline'),
  ('BestBuy CA', 'bestbuy.ca', 'Canada', 'ca.BestBuy'),
  ('Canadian Tire CA', 'canadiantire.ca', 'Canada', 'ca.CanadianTire'),
  ('Walmart CA', 'walmart.ca', 'Canada', 'ca.Walmart'),
  ('Notebooks Billiger DE', 'notebooksbilliger.de', 'Germany', 'de.NotebooksBilliger'),
  ('Otto DE', 'otto.de', 'Germany', 'de.Otto'),
  ('Electro King ES', 'electroking.es', 'Spain', 'es.ElectroKing'),
  ('101 Gigas ES', '101gigas.com', 'Spain', 'es.Gigas101'),
  ('Pixmania ES', 'pixmania.es', 'Spain', 'es.Pixmania'),
  ('UlaBox ES', 'ulabox.com', 'Spain', 'es.UlaBox'),
  ('Auchan FR', 'auchan.fr', 'France', 'fr.Auchan'),
  ('CDiscount FR', 'cdiscount.com', 'France', 'fr.CDiscount'),
  ('Fnac FR', 'fnac.com', 'France', 'fr.Fnac'),
  ('Laredoute FR', 'laredoute.fr', 'France', 'fr.Laredoute'),
  ('EPrice IT', 'eprice.it', 'Italy', 'it.EPrice'),
  ('Euronics IT', 'euronics.it', 'Italy', 'it.Euronics'),
  ('MediaWorld IT', 'mediaworld.it', 'Italy', 'it.MediaWorld'),
  ('VidaXL IT', 'vidaxl.it', 'Italy', 'it.VidaXL'),
  ('Bol NL', 'bol.com', 'Netherlands', 'nl.Bol'),
  ('CoolBlue NL', 'coolblue.nl', 'Netherlands', 'nl.CoolBlue'),
  ('De Bijenkorf NL', 'debijenkorf.nl', 'Netherlands', 'nl.DeBijenkorf'),
  ('Wehkamp NL', 'wehkamp.nl', 'Netherlands', 'nl.Wehkamp'),
  ('Gittigidiyor TR', 'gittigidiyor.com', 'Turkey', 'tr.GittiGidiyor'),
  ('Hepsiburada TR', 'hepsiburada.com', 'Turkey', 'tr.HepsiBurada'),
  ('n11 TR', 'n11.com', 'Turkey', 'tr.N11'),
  ('Teknosa TR', 'teknosa.com', 'Turkey', 'tr.Teknosa'),
  ('Trendyol TR', 'trendyol.com', 'Turkey', 'tr.Trendyol'),
  ('Argos UK', 'argos.co.uk', 'United Kingdom', 'uk.Argos'),
  ('Asda UK', 'groceries.argos.com', 'United Kingdom', 'uk.Asda'),
  ('Asos UK', 'asos.com', 'United Kingdom', 'uk.Asos'),
  ('Currys UK', 'currys.co.uk', 'United Kingdom', 'uk.Currys'),
  ('Debenhams UK', 'debenhams.com', 'United Kingdom', 'uk.Debenhams'),
  ('NewLook UK', 'newlook.com', 'United Kingdom', 'uk.NewLook'),
  ('Zavvi UK', 'zavvi.com', 'United Kingdom', 'uk.Zavvi')
  ;

-- problematic implementations
insert into platform (name, domain, country, class_name, status, problem) values
  ('Harvey Norman AU', 'harveynorman.com.au', 'Australia', 'au.HarveyNorman', 'IMPROPER', 'Data access problem!');
